# Generated by Django 5.1.6 on 2025-02-27 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Blog_content', models.TextField(null=True)),
                ('Image', models.ImageField(null=True, upload_to='')),
                ('Date_blog', models.DateField(auto_now_add=True, null=True)),
                ('Approval_status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_title', models.CharField(max_length=200, null=True)),
                ('Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter_title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Message_content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter_Content', models.FileField(null=True, upload_to='media')),
                ('Chapter_text_content', models.TextField(max_length=900, null=True)),
                ('Chapter_Content_type', models.CharField(max_length=200, null=True)),
                ('cont_cha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.CharField(max_length=200, null=True)),
                ('Course_brief', models.TextField(null=True)),
                ('Course_duration', models.IntegerField(null=True)),
                ('Course_fee', models.FloatField(null=True)),
                ('Language', models.CharField(max_length=200, null=True)),
                ('cou_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_to_category', to='learn.category')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='cha_cou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.course'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_topic', models.CharField(max_length=200, null=True)),
                ('assignment_upload', models.FileField(null=True, upload_to='')),
                ('total_marks', models.CharField(max_length=200, null=True)),
                ('pass_percent', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(null=True)),
                ('submission_date', models.DateField(null=True)),
                ('assign_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_to_course', to='learn.course')),
            ],
        ),
        migrations.CreateModel(
            name='Course_st_stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('cou_st_stop_cou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_st_stop_to_course', to='learn.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pending_days', models.IntegerField(null=True)),
                ('Enrollment_date', models.DateField(auto_now_add=True, null=True)),
                ('Teacher_response', models.CharField(max_length=200, null=True)),
                ('Teacher_approval', models.CharField(max_length=200, null=True)),
                ('Course_completion_status', models.CharField(max_length=200, null=True)),
                ('Payment_status', models.CharField(max_length=200, null=True)),
                ('Certificate', models.FileField(null=True, upload_to='')),
                ('notify', models.CharField(max_length=200, null=True)),
                ('enrol_cou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrolled', to='learn.course')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=200, null=True)),
                ('Registration_date', models.DateField(auto_now_add=True, null=True)),
                ('Num_of_courses_enrolled', models.IntegerField(null=True)),
                ('Num_of_courses_completed', models.IntegerField(null=True)),
                ('Qualification', models.TextField(null=True)),
                ('Introduction_brief', models.TextField(null=True)),
                ('Image', models.ImageField(null=True, upload_to='media')),
                ('Num_of_enrolled_students', models.IntegerField(null=True)),
                ('Average_review_rating', models.IntegerField(null=True)),
                ('Num_of_reviews', models.IntegerField(null=True)),
                ('About_website', models.TextField(null=True)),
                ('Registration_fee', models.IntegerField(null=True)),
                ('User_role', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message_content', models.TextField(null=True)),
                ('From_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_message', to='learn.registration')),
                ('To_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_message', to='learn.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldate', models.TimeField(null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('enrol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liv_to_enrol', to='learn.enrollment')),
                ('liv_tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liv_to_tea_reg', to='learn.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Learning_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Begin_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Completion_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('Status', models.CharField(max_length=200, null=True)),
                ('Learn_p_cnt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress_to_content', to='learn.content')),
                ('Learn_p_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_progress_to_st_reg', to='learn.registration')),
                ('Learn_p_tea_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_progress_to_tea_reg', to='learn.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating_score', models.IntegerField(null=True)),
                ('Feedback_text', models.TextField(null=True)),
                ('Submission_date', models.DateField(auto_now_add=True, null=True)),
                ('Feed_cou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_to_course', to='learn.course')),
                ('Feed_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_st_reg', to='learn.registration')),
                ('Feed_tea_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tea_reg', to='learn.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_marks', models.IntegerField(null=True)),
                ('Acquired_marks', models.IntegerField(null=True)),
                ('Grade', models.CharField(max_length=200, null=True)),
                ('Time_stop', models.DateTimeField(auto_now=True, null=True)),
                ('Exam_res_cou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_res_to_course', to='learn.course')),
                ('Exam_res_reg_st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_res_to_student', to='learn.registration')),
                ('Exam_res_reg_tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_res_to_teacher', to='learn.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_reg_cou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_register_course', to='learn.course')),
                ('ex_reg_st_enroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register_student_enrollment', to='learn.enrollment')),
                ('ex_reg_st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register_student', to='learn.registration')),
                ('ex_reg_tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_register_teacher', to='learn.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(null=True)),
                ('Option1', models.TextField(null=True)),
                ('Option2', models.TextField(null=True)),
                ('Option3', models.TextField(null=True)),
                ('Correct_answer', models.TextField(null=True)),
                ('Lock', models.CharField(max_length=200, null=True)),
                ('Time_start', models.DateTimeField(null=True)),
                ('Time_stop', models.DateTimeField(null=True)),
                ('Exam_cou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_to_course', to='learn.course')),
                ('Exam_reg_st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_to_student', to='learn.registration')),
                ('Exam_reg_tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_to_teacher', to='learn.registration')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrol_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrolled', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrol_tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_teaching', to='learn.registration'),
        ),
        migrations.AddField(
            model_name='course',
            name='cou_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Course_to_registration', to='learn.registration'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_tim', models.DateTimeField(auto_now_add=True, null=True)),
                ('Attendance_done_location', models.CharField(max_length=200, null=True)),
                ('atten_enroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_to_enroll', to='learn.enrollment')),
                ('atten_stud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_to_student', to='learn.registration')),
                ('atten_tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_to_teacher', to='learn.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_upload_ans', models.FileField(null=True, upload_to='')),
                ('acquired_marks', models.CharField(max_length=200, null=True)),
                ('acquired_pass_percent', models.CharField(max_length=200, null=True)),
                ('asssi_res_assi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_result_assi', to='learn.assignment')),
                ('asssi_res_st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_result_student', to='learn.registration')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_tea_reg', to='learn.registration'),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('User_category', models.CharField(max_length=200, null=True)),
                ('Old_password', models.CharField(max_length=200, null=True)),
                ('New_password', models.CharField(max_length=200, null=True)),
                ('Req_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learn.registration')),
            ],
        ),
    ]
